import numpy as np
needs = {
    'Sense of Power': 'The power, force and energy to accomplish the goal',
    'Contribution': np.random.rand(),
    'Sense of Control': np.random.rand(),
    'Enjoyment': np.random.rand(),
    'Peacefulness': np.random.rand(),
    'Challenge': np.random.rand(),
    'Respite': np.random.rand(),
    'Expression': np.random.rand(),
    'Purpose': np.random.rand(),
    'Productivity': np.random.rand(),
    'Health': np.random.rand(),
    'Self-Acceptance': np.random.rand(),
    'Freedom': np.random.rand(),
    'Sense of Importance': np.random.rand(),
    'Comfort': np.random.rand(),
    'Understanding': np.random.rand(),
    'Contentment': np.random.rand(),
    'Significance': np.random.rand(),
    'Constructive': np.random.rand(),
    'Objectivity': np.random.rand(),
    'Skill Training': np.random.rand(),
    'Boundaries': np.random.rand(),
    'Opportunity': np.random.rand(),
    'Safety': np.random.rand(),
    'Sense of Identity': np.random.rand(),
    'Affection': np.random.rand(),
    'Accountability': np.random.rand(),
    'Trust': np.random.rand(),
    'Worthiness': np.random.rand(),
    'Fun': np.random.rand(),
    'Appreciation': np.random.rand(),
    'Concern': np.random.rand(),
    'Empathy': np.random.rand(),
    'Forgiveness-Mercy': np.random.rand(),
    'Feedback': np.random.rand(),
    'Gentleness': np.random.rand(),
    'Consequences': np.random.rand(),
    'Encouragement': np.random.rand(),
    'Structure': np.random.rand(),
    'Honesty': np.random.rand(),
    'Information': np.random.rand(),
    'Fairness': np.random.rand(),
    'Standards': np.random.rand(),
    'Reward': np.random.rand(),
    'Inspiration': np.random.rand(),
    'Correction': np.random.rand(),
    'Discipline': np.random.rand(),
    'Affirmation': np.random.rand(),
    'Belonging': np.random.rand(),
    'Genuineness': np.random.rand(),
    'Clarity': np.random.rand(),
    'Guidance': np.random.rand(),
    'Attention': np.random.rand(),
    'Interest': np.random.rand(),
    'Acceptance': np.random.rand()
}